### PR TITLE
Allow vitest 2 via peer deps

### PR DESCRIPTION
**Pull request by saitonakamura**
the lib seems to work fine with vitest 2 and I don't see any breaking changes affecting it https://github.com/vitest-dev/vitest/releases/tag/v2.0.0

the tests and examples work fine and our usage of this lib with vitest also doesn't show any problems

### CODE REVIEW

**Comment by saitonakamura** [comment]
I need to reconfigure coverage as well from what I see

**Comment by saitonakamura** [comment]
Also the #42 will definitely conflict with this one, so I need to wait and rebase after it merges

**Comment by penpenpng** [comment]
> Also the #42 will definitely conflict with this one, so I need to wait and rebase after it merges

@saitonakamura Hi, #42 has been merged. Could you fix the conflict?

**Comment by saitonakamura** [comment]
Yeah, let's do this

**Comment by saitonakamura** [comment]
In #42 vitest was bumped to v2, so this MR is no longer relevant unless we want to still allow vitest v1

**Comment by saitonakamura** [comment]
Closing it, feel free to reopen

**Pull request closed without merging**
